FROM golang:1.21

WORKDIR /go/src
ENV PATH="/go/bin:${PATH}"
ENV GO111MODULE=on
ENV CGO_ENABLED=1

RUN apt-get update && \
    apt-get install build-essential -y

COPY . .

RUN GOOS=linux go build -ldflags="-s -w" -o transaction-product-wex

ENTRYPOINT ["./transaction-product-wex"]