version: "3"

services:
  app:
    build: .
    env_file:
      - .env
    volumes:
      - .:/go/src/
    ports:
      - "8888:8888"

  db:
    image: postgres:9.4
    restart: always
    tty: true
    env_file:
      - .env
    volumes:
      - .pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_USER}
    ports:
      - "5432:5432"

  cache:
    image: redis:7.2
    volumes:
      - .redis-persistence:/var/lib/redis/data
    env_file:
      - .env
    command: redis-server --requirepass ${CACHE_PASSWORD}
    ports:
      - "6379:6379"
