name: Run tests

on: [push, pull_request]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21
      - name: Run tests
        run: go test ./...
